name: wordseg
dependencies:
  # installation
  - cmake
  # package
  - cloudpickle=0.5.6  # avoid a warning in wordseg-eval
  - joblib
  - python>=3.7
  - scikit-learn
  - six
  # test
  - pytest>=5.0
  - pytest-cov
  # documentation
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
