name: wordseg
dependencies:
  # package
  - cloudpickle=0.5.6  # avoid a warning in wordseg-eval
  - joblib
  - python=3.7
  - scikit-learn
  - six
  # test
  - pytest
  # documentation
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
